# used for tests only

services:
  elastic8:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.0
    restart: always
    environment:
      discovery.type: single-node
      network.host: 0.0.0.0
      xpack.security.http.ssl.enabled: false
      xpack.security.enabled: false
      # https://github.com/elastic/elasticsearch/issues/118583#issuecomment-2578368306
      ES_JAVA_OPTS: -XX:UseSVE=0
      CLI_JAVA_OPTS: -XX:UseSVE=0
    ports:
      - 9220:9200
      - 9320:9300
    deploy:
      resources:
        limits:
          memory: 1024M
